apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "local-path-provisioner.fullname" . }}
  labels:
    {{- include "local-path-provisioner.labels" . | nindent 4 }}
provisioner: rancher.io/local-path
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
