apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakroles.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories: []
    kind: KeycloakRole
    plural: keycloakroles
    shortNames:
    - kcr
    singular: keycloakrole
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ''
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: ''
      jsonPath: .status.status
      name: Status
      type: string
    - description: ''
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: resource to define a Protocol Mapper within either a [KeycloakRealm](./keycloakrealm.md) or a [KeycloakClient](./keycloakclient.md)
        properties:
          spec:
            anyOf:
            - required:
              - realmRef
            - required:
              - clientRef
            description: the KeycloakRole resource
            properties:
              clientRef:
                type: string
              definition:
                properties:
                  attributes:
                    additionalProperties:
                      items:
                        type: string
                      type: array
                    nullable: true
                    type: object
                  clientRole:
                    nullable: true
                    type: boolean
                  composite:
                    nullable: true
                    type: boolean
                  composites:
                    nullable: true
                    properties:
                      application:
                        additionalProperties:
                          items:
                            type: string
                          type: array
                        nullable: true
                        type: object
                      client:
                        additionalProperties:
                          items:
                            type: string
                          type: array
                        nullable: true
                        type: object
                      realm:
                        items:
                          type: string
                        nullable: true
                        type: array
                    type: object
                  containerId:
                    nullable: true
                    type: string
                  description:
                    nullable: true
                    type: string
                  id:
                    nullable: true
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  name:
                    nullable: true
                    type: string
                  scopeParamRequired:
                    nullable: true
                    type: boolean
                type: object
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: has(self.id) == has(oldSelf.id)
              options:
                description: Options for the request to the Keycloak Admin API.
                nullable: true
                type: object
              realmRef:
                type: string
            required:
            - definition
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    lastUpdateTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                nullable: true
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakRole
        type: object
    served: true
    storage: true
    subresources:
      status: {}
