apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakidentityprovidermappers.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories: []
    kind: KeycloakIdentityProviderMapper
    plural: keycloakidentityprovidermappers
    shortNames:
    - kcipm
    singular: keycloakidentityprovidermapper
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ''
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: ''
      jsonPath: .status.status
      name: Status
      type: string
    - description: ''
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: resource to define a identity provider mapper within a [KeyclaokIdentityProvider](./keycloakidentityprovider.md)
        properties:
          spec:
            description: the KeycloakIdentityProviderMapper resource
            properties:
              definition:
                properties:
                  config:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                  id:
                    nullable: true
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  identityProviderAlias:
                    nullable: true
                    type: string
                  identityProviderMapper:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                type: object
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: has(self.id) == has(oldSelf.id)
              identityProviderRef:
                description: the name of the kubernetes object that created the identity provider.
                type: string
              options:
                description: Options for the request to the Keycloak Admin API.
                nullable: true
                type: object
            required:
            - definition
            - identityProviderRef
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    lastUpdateTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                nullable: true
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakIdentityProviderMapper
        type: object
    served: true
    storage: true
    subresources:
      status: {}
