apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakprotocolmappers.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories: []
    kind: KeycloakProtocolMapper
    plural: keycloakprotocolmappers
    shortNames:
    - kcpm
    singular: keycloakprotocolmapper
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ''
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: ''
      jsonPath: .status.status
      name: Status
      type: string
    - description: ''
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: resource to define a Protocol Mapper within either a [KeycloakClient](./keycloakclient.md) or a [KeycloakClientScope](./keycloakclientscope.md)
        properties:
          spec:
            anyOf:
            - required:
              - clientRef
            - required:
              - clientScopeRef
            description: the KeycloakProtocolMapper resource
            properties:
              clientRef:
                type: string
              clientScopeRef:
                type: string
              definition:
                properties:
                  config:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                  consentRequired:
                    nullable: true
                    type: boolean
                  consentText:
                    nullable: true
                    type: string
                  id:
                    nullable: true
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  name:
                    nullable: true
                    type: string
                  protocol:
                    nullable: true
                    type: string
                  protocolMapper:
                    nullable: true
                    type: string
                type: object
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: has(self.id) == has(oldSelf.id)
              options:
                description: Options for the request to the Keycloak Admin API.
                nullable: true
                type: object
            required:
            - definition
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    lastUpdateTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                nullable: true
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakProtocolMapper
        type: object
    served: true
    storage: true
    subresources:
      status: {}
