apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrequiredactionproviders.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories: []
    kind: KeycloakRequiredActionProvider
    plural: keycloakrequiredactionproviders
    shortNames:
    - kcrap
    singular: keycloakrequiredactionprovider
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ''
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: ''
      jsonPath: .status.status
      name: Status
      type: string
    - description: ''
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: resource to define an Required Action Provider within a [KeyclaokRealm](./keycloakrealm.md)
        properties:
          spec:
            description: the KeycloakRequiredActionProvider resource
            properties:
              definition:
                properties:
                  alias:
                    nullable: true
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  config:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                  defaultAction:
                    nullable: true
                    type: boolean
                  enabled:
                    nullable: true
                    type: boolean
                  name:
                    nullable: true
                    type: string
                  priority:
                    format: int32
                    nullable: true
                    type: integer
                  providerId:
                    nullable: true
                    type: string
                type: object
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: has(self.alias) == has(oldSelf.alias)
              options:
                description: Options for the request to the Keycloak Admin API.
                nullable: true
                type: object
              realmRef:
                description: the name of the kubernetes object that created the realm.
                type: string
            required:
            - definition
            - realmRef
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    lastUpdateTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                nullable: true
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakRequiredActionProvider
        type: object
    served: true
    storage: true
    subresources:
      status: {}
