apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakusers.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories:
    - keycloak
    - all
    kind: KeycloakUser
    plural: keycloakusers
    shortNames:
    - kcu
    singular: keycloakuser
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: true if the realm is ready
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: Status String of the resource
      jsonPath: .status.status
      name: Status
      type: string
    - description: time since the realm was created
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: resource to define a User within a [KeyclaokRealm](./keycloakrealm.md)
        properties:
          spec:
            description: the KeycloakUser resource
            properties:
              definition:
                properties:
                  access:
                    additionalProperties:
                      type: boolean
                    nullable: true
                    type: object
                  applicationRoles:
                    additionalProperties:
                      items:
                        type: string
                      type: array
                    nullable: true
                    type: object
                  attributes:
                    additionalProperties:
                      items:
                        type: string
                      type: array
                    nullable: true
                    type: object
                  clientConsents:
                    items:
                      properties:
                        clientId:
                          nullable: true
                          type: string
                        createdDate:
                          format: int64
                          nullable: true
                          type: integer
                        grantedClientScopes:
                          items:
                            type: string
                          nullable: true
                          type: array
                        grantedRealmRoles:
                          items:
                            type: string
                          nullable: true
                          type: array
                        lastUpdatedDate:
                          format: int64
                          nullable: true
                          type: integer
                      type: object
                    nullable: true
                    type: array
                  clientRoles:
                    additionalProperties:
                      items:
                        type: string
                      type: array
                    nullable: true
                    type: object
                  createdTimestamp:
                    format: int64
                    nullable: true
                    type: integer
                  credentials:
                    items:
                      properties:
                        algorithm:
                          nullable: true
                          type: string
                        config:
                          additionalProperties:
                            items:
                              type: string
                            type: array
                          nullable: true
                          type: object
                        counter:
                          format: int32
                          nullable: true
                          type: integer
                        createdDate:
                          format: int64
                          nullable: true
                          type: integer
                        credentialData:
                          nullable: true
                          type: string
                        device:
                          nullable: true
                          type: string
                        digits:
                          format: int32
                          nullable: true
                          type: integer
                        hashIterations:
                          format: int32
                          nullable: true
                          type: integer
                        hashedSaltedValue:
                          nullable: true
                          type: string
                        id:
                          nullable: true
                          type: string
                        period:
                          format: int32
                          nullable: true
                          type: integer
                        priority:
                          format: int32
                          nullable: true
                          type: integer
                        salt:
                          nullable: true
                          type: string
                        secretData:
                          nullable: true
                          type: string
                        temporary:
                          nullable: true
                          type: boolean
                        type:
                          nullable: true
                          type: string
                        userLabel:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  disableableCredentialTypes:
                    items:
                      type: string
                    nullable: true
                    type: array
                  email:
                    nullable: true
                    type: string
                  emailVerified:
                    nullable: true
                    type: boolean
                  enabled:
                    nullable: true
                    type: boolean
                  federatedIdentities:
                    items:
                      properties:
                        identityProvider:
                          nullable: true
                          type: string
                        userId:
                          nullable: true
                          type: string
                        userName:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  federationLink:
                    nullable: true
                    type: string
                  firstName:
                    nullable: true
                    type: string
                  groups:
                    items:
                      type: string
                    nullable: true
                    type: array
                  id:
                    nullable: true
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  lastName:
                    nullable: true
                    type: string
                  notBefore:
                    format: int32
                    nullable: true
                    type: integer
                  origin:
                    nullable: true
                    type: string
                  realmRoles:
                    items:
                      type: string
                    nullable: true
                    type: array
                  requiredActions:
                    items:
                      type: string
                    nullable: true
                    type: array
                  self:
                    nullable: true
                    type: string
                  serviceAccountClientId:
                    nullable: true
                    type: string
                  socialLinks:
                    items:
                      properties:
                        socialProvider:
                          nullable: true
                          type: string
                        socialUserId:
                          nullable: true
                          type: string
                        socialUsername:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  totp:
                    nullable: true
                    type: boolean
                  userProfileMetadata:
                    nullable: true
                    properties:
                      attributes:
                        items:
                          properties:
                            annotations:
                              additionalProperties: true
                              nullable: true
                              type: object
                            displayName:
                              nullable: true
                              type: string
                            group:
                              nullable: true
                              type: string
                            multivalued:
                              nullable: true
                              type: boolean
                            name:
                              nullable: true
                              type: string
                            readOnly:
                              nullable: true
                              type: boolean
                            required:
                              nullable: true
                              type: boolean
                            validators:
                              additionalProperties:
                                additionalProperties: true
                                type: object
                              nullable: true
                              type: object
                          type: object
                        nullable: true
                        type: array
                      groups:
                        items:
                          properties:
                            annotations:
                              additionalProperties: true
                              nullable: true
                              type: object
                            displayDescription:
                              nullable: true
                              type: string
                            displayHeader:
                              nullable: true
                              type: string
                            name:
                              nullable: true
                              type: string
                          type: object
                        nullable: true
                        type: array
                    type: object
                  username:
                    nullable: true
                    type: string
                type: object
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: has(self.id) == has(oldSelf.id)
              options:
                description: Options for the request to the Keycloak Admin API.
                nullable: true
                type: object
              patchFrom:
                additionalProperties:
                  description: EnvVarSource represents a source for the value of an EnvVar.
                  properties:
                    configMapKeyRef:
                      description: Selects a key of a ConfigMap.
                      properties:
                        key:
                          description: The key to select.
                          type: string
                        name:
                          description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        optional:
                          description: Specify whether the ConfigMap or its key must be defined
                          type: boolean
                      required:
                      - key
                      - name
                      type: object
                    fieldRef:
                      description: 'Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels[''<KEY>'']`, `metadata.annotations[''<KEY>'']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.'
                      properties:
                        apiVersion:
                          description: Version of the schema the FieldPath is written in terms of, defaults to "v1".
                          type: string
                        fieldPath:
                          description: Path of the field to select in the specified API version.
                          type: string
                      required:
                      - fieldPath
                      type: object
                    resourceFieldRef:
                      description: 'Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.'
                      properties:
                        containerName:
                          description: 'Container name: required for volumes, optional for env vars'
                          type: string
                        divisor:
                          description: Specifies the output format of the exposed resources, defaults to "1"
                          type: string
                        resource:
                          description: 'Required: resource to select'
                          type: string
                      required:
                      - resource
                      type: object
                    secretKeyRef:
                      description: Selects a key of a secret in the pod's namespace
                      properties:
                        key:
                          description: The key of the secret to select from.  Must be a valid secret key.
                          type: string
                        name:
                          description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        optional:
                          description: Specify whether the Secret or its key must be defined
                          type: boolean
                      required:
                      - key
                      - name
                      type: object
                    valueAs:
                      enum:
                      - auto
                      - string
                      - number
                      - yaml
                      - json
                      - bool
                      nullable: true
                      type: string
                  type: object
                description: Defines additional values that can be loaded from secrets or configmaps. Field selectors are not supported. For more informations see [the patches documentation](../configuration/patches.md).
                type: object
              realmRef:
                description: the name of the kubernetes object that created the realm.
                type: string
              userSecret:
                nullable: true
                properties:
                  passwordKey:
                    nullable: true
                    type: string
                  secretName:
                    type: string
                  usernameKey:
                    nullable: true
                    type: string
                required:
                - secretName
                type: object
            required:
            - definition
            - realmRef
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    lastUpdateTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                nullable: true
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakUser
        type: object
    served: true
    storage: true
    subresources:
      status: {}
