apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakorganizations.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories: []
    kind: KeycloakOrganization
    plural: keycloakorganizations
    shortNames:
    - kcorg
    singular: keycloakorganization
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ''
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: ''
      jsonPath: .status.status
      name: Status
      type: string
    - description: ''
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: resource to define an Organisation within a [KeyclaokRealm](./keycloakrealm.md)
        properties:
          spec:
            description: the KeycloakOrganization resource
            properties:
              definition:
                properties:
                  alias:
                    nullable: true
                    type: string
                  attributes:
                    additionalProperties:
                      items:
                        type: string
                      type: array
                    nullable: true
                    type: object
                  description:
                    nullable: true
                    type: string
                  domains:
                    items:
                      properties:
                        name:
                          nullable: true
                          type: string
                        verified:
                          nullable: true
                          type: boolean
                      type: object
                    nullable: true
                    type: array
                  enabled:
                    nullable: true
                    type: boolean
                  id:
                    nullable: true
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  identityProviders:
                    items:
                      properties:
                        addReadTokenRoleOnCreate:
                          nullable: true
                          type: boolean
                        alias:
                          nullable: true
                          type: string
                        authenticateByDefault:
                          nullable: true
                          type: boolean
                        config:
                          additionalProperties:
                            type: string
                          nullable: true
                          type: object
                        displayName:
                          nullable: true
                          type: string
                        enabled:
                          nullable: true
                          type: boolean
                        firstBrokerLoginFlowAlias:
                          nullable: true
                          type: string
                        hideOnLogin:
                          nullable: true
                          type: boolean
                        internalId:
                          nullable: true
                          type: string
                        linkOnly:
                          nullable: true
                          type: boolean
                        organizationId:
                          nullable: true
                          type: string
                        postBrokerLoginFlowAlias:
                          nullable: true
                          type: string
                        providerId:
                          nullable: true
                          type: string
                        storeToken:
                          nullable: true
                          type: boolean
                        trustEmail:
                          nullable: true
                          type: boolean
                        updateProfileFirstLogin:
                          nullable: true
                          type: boolean
                        updateProfileFirstLoginMode:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  members:
                    items:
                      properties:
                        access:
                          additionalProperties:
                            type: boolean
                          nullable: true
                          type: object
                        applicationRoles:
                          additionalProperties:
                            items:
                              type: string
                            type: array
                          nullable: true
                          type: object
                        attributes:
                          additionalProperties:
                            items:
                              type: string
                            type: array
                          nullable: true
                          type: object
                        clientConsents:
                          items:
                            properties:
                              clientId:
                                nullable: true
                                type: string
                              createdDate:
                                format: int64
                                nullable: true
                                type: integer
                              grantedClientScopes:
                                items:
                                  type: string
                                nullable: true
                                type: array
                              grantedRealmRoles:
                                items:
                                  type: string
                                nullable: true
                                type: array
                              lastUpdatedDate:
                                format: int64
                                nullable: true
                                type: integer
                            type: object
                          nullable: true
                          type: array
                        clientRoles:
                          additionalProperties:
                            items:
                              type: string
                            type: array
                          nullable: true
                          type: object
                        createdTimestamp:
                          format: int64
                          nullable: true
                          type: integer
                        credentials:
                          items:
                            properties:
                              algorithm:
                                nullable: true
                                type: string
                              config:
                                additionalProperties:
                                  items:
                                    type: string
                                  type: array
                                nullable: true
                                type: object
                              counter:
                                format: int32
                                nullable: true
                                type: integer
                              createdDate:
                                format: int64
                                nullable: true
                                type: integer
                              credentialData:
                                nullable: true
                                type: string
                              device:
                                nullable: true
                                type: string
                              digits:
                                format: int32
                                nullable: true
                                type: integer
                              hashIterations:
                                format: int32
                                nullable: true
                                type: integer
                              hashedSaltedValue:
                                nullable: true
                                type: string
                              id:
                                nullable: true
                                type: string
                              period:
                                format: int32
                                nullable: true
                                type: integer
                              priority:
                                format: int32
                                nullable: true
                                type: integer
                              salt:
                                nullable: true
                                type: string
                              secretData:
                                nullable: true
                                type: string
                              temporary:
                                nullable: true
                                type: boolean
                              type:
                                nullable: true
                                type: string
                              userLabel:
                                nullable: true
                                type: string
                              value:
                                nullable: true
                                type: string
                            type: object
                          nullable: true
                          type: array
                        disableableCredentialTypes:
                          items:
                            type: string
                          nullable: true
                          type: array
                        email:
                          nullable: true
                          type: string
                        emailVerified:
                          nullable: true
                          type: boolean
                        enabled:
                          nullable: true
                          type: boolean
                        federatedIdentities:
                          items:
                            properties:
                              identityProvider:
                                nullable: true
                                type: string
                              userId:
                                nullable: true
                                type: string
                              userName:
                                nullable: true
                                type: string
                            type: object
                          nullable: true
                          type: array
                        federationLink:
                          nullable: true
                          type: string
                        firstName:
                          nullable: true
                          type: string
                        groups:
                          items:
                            type: string
                          nullable: true
                          type: array
                        id:
                          nullable: true
                          type: string
                        lastName:
                          nullable: true
                          type: string
                        membershipType:
                          enum:
                          - UNMANAGED
                          - MANAGED
                          nullable: true
                          type: string
                        notBefore:
                          format: int32
                          nullable: true
                          type: integer
                        origin:
                          nullable: true
                          type: string
                        realmRoles:
                          items:
                            type: string
                          nullable: true
                          type: array
                        requiredActions:
                          items:
                            type: string
                          nullable: true
                          type: array
                        self:
                          nullable: true
                          type: string
                        serviceAccountClientId:
                          nullable: true
                          type: string
                        socialLinks:
                          items:
                            properties:
                              socialProvider:
                                nullable: true
                                type: string
                              socialUserId:
                                nullable: true
                                type: string
                              socialUsername:
                                nullable: true
                                type: string
                            type: object
                          nullable: true
                          type: array
                        totp:
                          nullable: true
                          type: boolean
                        userProfileMetadata:
                          nullable: true
                          properties:
                            attributes:
                              items:
                                properties:
                                  annotations:
                                    additionalProperties: true
                                    nullable: true
                                    type: object
                                  displayName:
                                    nullable: true
                                    type: string
                                  group:
                                    nullable: true
                                    type: string
                                  multivalued:
                                    nullable: true
                                    type: boolean
                                  name:
                                    nullable: true
                                    type: string
                                  readOnly:
                                    nullable: true
                                    type: boolean
                                  required:
                                    nullable: true
                                    type: boolean
                                  validators:
                                    additionalProperties:
                                      additionalProperties: true
                                      type: object
                                    nullable: true
                                    type: object
                                type: object
                              nullable: true
                              type: array
                            groups:
                              items:
                                properties:
                                  annotations:
                                    additionalProperties: true
                                    nullable: true
                                    type: object
                                  displayDescription:
                                    nullable: true
                                    type: string
                                  displayHeader:
                                    nullable: true
                                    type: string
                                  name:
                                    nullable: true
                                    type: string
                                type: object
                              nullable: true
                              type: array
                          type: object
                        username:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  name:
                    nullable: true
                    type: string
                  redirectUrl:
                    nullable: true
                    type: string
                type: object
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: has(self.id) == has(oldSelf.id)
              options:
                description: Options for the request to the Keycloak Admin API.
                nullable: true
                type: object
              realmRef:
                description: the name of the kubernetes object that created the realm.
                type: string
            required:
            - definition
            - realmRef
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    lastUpdateTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                nullable: true
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakOrganization
        type: object
    served: true
    storage: true
    subresources:
      status: {}
