{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "keycloak-operator-legacy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "keycloak-operator-legacy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "keycloak-operator-legacy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
