{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rustcloak-operator.serviceAccountName" . }}
  labels:
    {{- include "rustcloak-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - rustcloak.k8s.eboland.de
  resources:
    - keycloakapiobjects/status
    - keycloakauthenticationflows/status
    - keycloakauthenticatorconfigs/status
    - keycloakclients/status
    - keycloakclientscopes/status
    - keycloakcomponents/status
    - keycloakgroups/status
    - keycloakidentityprovidermappers/status
    - keycloakidentityproviders/status
    - keycloakinstances/status
    - keycloakorganizations/status
    - keycloakprotocolmappers/status
    - keycloakrealms/status
    - keycloakrequiredactionproviders/status
    - keycloakresources/status
    - keycloakroles/status
    - keycloakscopes/status
    - keycloakusers/status
  verbs:
    - patch
    - get
- apiGroups:
  - rustcloak.k8s.eboland.de
  resources:
    - keycloakapiobjects
    - keycloakauthenticationflows
    - keycloakauthenticatorconfigs
    - keycloakclients
    - keycloakclientscopes
    - keycloakcomponents
    - keycloakgroups
    - keycloakidentityprovidermappers
    - keycloakidentityproviders
    - keycloakinstances
    - keycloakorganizations
    - keycloakprotocolmappers
    - keycloakrealms
    - keycloakrequiredactionproviders
    - keycloakresources
    - keycloakroles
    - keycloakscopes
    - keycloakusers
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
    - create
    - update
    - patch
    - delete
{{- end }}
